# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Steckdosen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QPushButton, QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(446, 120)
        self.centralwidget = QMainWindow
        self.centralwidget.setObjectName("centralwidget")
        self.pb1 = QtWidgets.QPushButton(self.centralwidget)
        self.pb1.setGeometry(QtCore.QRect(0, 10, 84, 28))
        self.pb1.setObjectName("pb1")
        self.pb2 = QtWidgets.QPushButton(self.centralwidget)
        self.pb2.setGeometry(QtCore.QRect(90, 10, 84, 28))
        self.pb2.setObjectName("pb2")
        self.pb3 = QtWidgets.QPushButton(self.centralwidget)
        self.pb3.setGeometry(QtCore.QRect(180, 10, 84, 28))
        self.pb3.setObjectName("pb3")
        self.pb4 = QtWidgets.QPushButton(self.centralwidget)
        self.pb4.setGeometry(QtCore.QRect(270, 10, 84, 28))
        self.pb4.setObjectName("pb4")
        self.pban = QtWidgets.QPushButton(self.centralwidget)
        self.pban.setGeometry(QtCore.QRect(360, 10, 84, 28))
        self.pban.setObjectName("pban")
        self.pb5 = QtWidgets.QPushButton(self.centralwidget)
        self.pb5.setGeometry(QtCore.QRect(0, 50, 84, 28))
        self.pb5.setObjectName("pb5")
        self.pb6 = QtWidgets.QPushButton(self.centralwidget)
        self.pb6.setGeometry(QtCore.QRect(90, 50, 84, 28))
        self.pb6.setObjectName("pb6")
        self.pb7 = QtWidgets.QPushButton(self.centralwidget)
        self.pb7.setGeometry(QtCore.QRect(180, 50, 84, 28))
        self.pb7.setObjectName("pb7")
        self.pb8 = QtWidgets.QPushButton(self.centralwidget)
        self.pb8.setGeometry(QtCore.QRect(270, 50, 84, 28))
        self.pb8.setObjectName("pb8")
        self.pbaus = QtWidgets.QPushButton(self.centralwidget)
        self.pbaus.setGeometry(QtCore.QRect(360, 50, 84, 28))
        self.pbaus.setObjectName("pbaus")
        self.pbText = QtWidgets.QPushButton(self.centralwidget)
        self.pbText.setGeometry(QtCore.QRect(30, 90, 84, 28))
        self.pbText.setObjectName("pbText")
        self.pbFarben = QtWidgets.QPushButton(self.centralwidget)
        self.pbFarben.setGeometry(QtCore.QRect(180, 90, 84, 28))
        self.pbFarben.setObjectName("pbFarben")
        self.pbPort = QtWidgets.QPushButton(self.centralwidget)
        self.pbPort.setGeometry(QtCore.QRect(330, 90, 84, 28))
        self.pbPort.setObjectName("pbPort")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb1.setText(_translate("MainWindow", "Steckdose 1"))
        self.pb2.setText(_translate("MainWindow", "Steckdose 2"))
        self.pb3.setText(_translate("MainWindow", "Steckdose 3"))
        self.pb4.setText(_translate("MainWindow", "Steckdose 4"))
        self.pban.setText(_translate("MainWindow", "Alle an"))
        self.pb5.setText(_translate("MainWindow", "Steckdose 5"))
        self.pb6.setText(_translate("MainWindow", "Steckdose 6"))
        self.pb7.setText(_translate("MainWindow", "Steckdose 7"))
        self.pb8.setText(_translate("MainWindow", "Steckdose8"))
        self.pbaus.setText(_translate("MainWindow", "Alle aus"))
        self.pbText.setText(_translate("MainWindow", "Text"))
        self.pbFarben.setText(_translate("MainWindow", "Farben"))
        self.pbPort.setText(_translate("MainWindow", "Port"))